eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    enable-replicated-request-compression: false # todo 经常掉线则判断为下线，而不是上线，仅能在开发环境使用

spring:
 application:
   name: eureka
server:
  port: 8761
